const items = [
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/04.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/03.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/02.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/01.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/04.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/03.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/02.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/01.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/08.jpeg", heading: "The Food of Bangladesh", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/07.jpeg", heading: "The Food of Saudia Arabia", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/06.jpeg", heading: "The Food of Polend", about: "Lecture aboud food", viwes: "10k viwes"},
    {clip:"youtube-images/05.jpeg", heading: "The Food of US and UK", about: "Lecture aboud food", viwes: "10k viwes"},
]
export default items;